server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://catalog-db:5432/catalog
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
