spring:
  datasource:
    url: jdbc:postgresql://reservations-db:5432/reservations
    username: reservations
    password: reservations
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

app:
  amqp:
    exchange: library.exchange
    queue: notifications-queue
    routingKey: notifications.route